services:
  stock-producer:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: stock-producer
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ../${ENV_FILE:-.env.docker}
